# Generated by Django 4.2.6 on 2023-12-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategorymodel',
            name='task',
        ),
    ]
