# Generated by Django 4.2.6 on 2023-12-24 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCard',
            new_name='AddCardModel',
        ),
        migrations.RenameField(
            model_name='addcardmodel',
            old_name='user',
            new_name='user_id',
        ),
    ]
