# Generated by Django 4.2.6 on 2023-12-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_image',
            field=models.ImageField(upload_to='car/', verbose_name='image'),
        ),
    ]
