# Generated by Django 4.2.6 on 2023-12-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_brandmodel_slug_alter_carmodel_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_decription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
