# Generated by Django 4.2.6 on 2023-12-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_carmodel_car_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
