# Generated by Django 4.2.6 on 2023-12-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
